/**
 * File generated from the NewModel::computer::Computer uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import computer.Memory;
import computer.Program;
import computer.ProgCounter;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Computer.
 */
public class Computer {
    /**
     * Description of the property memory.
     */
    private Memory memory = null;
    
    /**
     * Description of the property program.
     */
    private Program program = null;
    
    /**
     * Description of the property progCounter.
     */
    public ProgCounter progCounter = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Computer() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method load.
     * @param program 
     */
    public void load(Program program) {
    	// Start of user code for method load
    	// End of user code
    }
     
    /**
     * Description of the method run.
     */
    public void run() {
    	// Start of user code for method run
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns memory.
     * @return memory 
     */
    public Memory getMemory() {
    	return this.memory;
    }
    
    /**
     * Sets a value to attribute memory. 
     * @param newMemory 
     */
    public void setMemory(Memory newMemory) {
        this.memory = newMemory;
    }
    
    /**
     * Returns program.
     * @return program 
     */
    public Program getProgram() {
    	return this.program;
    }
    
    /**
     * Sets a value to attribute program. 
     * @param newProgram 
     */
    public void setProgram(Program newProgram) {
        this.program = newProgram;
    }
    
    /**
     * Returns progCounter.
     * @return progCounter 
     */
    public ProgCounter getProgCounter() {
    	return this.progCounter;
    }
    
    /**
     * Sets a value to attribute progCounter. 
     * @param newProgCounter 
     */
    public void setProgCounter(ProgCounter newProgCounter) {
        this.progCounter = newProgCounter;
    }
    
    
}
