/**
 * File generated from the NewModel::computer::Computer uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import computer.Memory;
import computer.Program;
import computer.ProgCounter;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Computer.
 */
public class Computer {
    /**
     * Description of the property memory.
     */
    private Memory memory = null;
    
    /**
     * Description of the property program.
     */
    private Program program = null;
    
    /**
     * Description of the property progCounter.
     */
    public ProgCounter progCounter = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Computer(Memory memory) {
    	this.memory = memory;
    }
    
    /**
     * Description of the method load.
     * @param program 
     */
    public void load(Program program) {
    	this.program=program;
    }
     
    /**
     * Description of the method run.
     */
    public void run() {
    	// Start of user code for method run
    	// End of user code
    }
    
    
}
