/**
 * File generated from the NewModel::computer::Computer uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import computer.Memory;
import computer.Program;
import computer.ProgCounter;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Computer.
 */
public class Computer {
    /**
     * Description of the property memory.
     */
    private Memory memory;

    private Program program;
    private ProgCounter progCounter;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Computer(Memory memory) {
    	this.memory = memory;
    	progCounter=new ProgCounter();
    }
    
    /**
     * Description of the method load.
     * @param program 
     */
    public void load(Program program) {
    	this.program=program;
    }
     
    /**
     * Description of the method run.
     */
    public void run() {
    	while(progCounter.getNext() >= 0){
    		program.get(progCounter.getNext()).exec(memory, progCounter);
    	}
    }
    
    
}
