/**
 * File generated from the NewModel::computer::LongMemory uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import operand.Address;
import operand.LongWord;
import operand.Word;
import computer.Memory;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of LongMemory.
 */
public class LongMemory implements Memory {
	
    LongWord[] memory;

    public LongMemory(int size) {
    	for(int i =0; i<size;i++){
			memory[i]= new LongWord(0);
		}
    }
    
    @Override
	public Word getWord(int address) {

		return memory[address];
	}
    
    
}
