/**
 * File generated from the NewModel::computer::LongMemory uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import operand.LongWord;
import computer.Memory;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of LongMemory.
 */
public class LongMemory extends Memory {
    /**
     * Description of the property memory.
     */
    public LongWord memory = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public LongMemory() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns memory.
     * @return memory 
     */
    public LongWord getMemory() {
    	return this.memory;
    }
    
    /**
     * Sets a value to attribute memory. 
     * @param newMemory 
     */
    public void setMemory(LongWord newMemory) {
        this.memory = newMemory;
    }
    
    
}
