/**
 * File generated from the NewModel::computer::Memory uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Memory.
 */
public abstract class Memory {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Memory() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
