/**
 * File generated from the NewModel::computer::Memory uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import operand.Word;

public interface Memory {

    public Word getWord(int address);

    
    
}
