/**
 * File generated from the NewModel::computer::ProgCounter uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ProgCounter.
 */
public class ProgCounter {
    /**
     * Description of the property next.
     */
    private Object next = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public ProgCounter() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method setTo.
     * @param nbr 
     */
    public void setTo(Object nbr) {
    	// Start of user code for method setTo
    	// End of user code
    }
     
    /**
     * Description of the method increase.
     */
    public void increase() {
    	// Start of user code for method increase
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns next.
     * @return next 
     */
    public Object getNext() {
    	return this.next;
    }
    
    /**
     * Sets a value to attribute next. 
     * @param newNext 
     */
    public void setNext(Object newNext) {
        this.next = newNext;
    }
    
    
}
