/**
 * File generated from the NewModel::computer::ProgCounter uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;


/**
 * Description of ProgCounter.
 */
public class ProgCounter {
    /**
     * Description of the property next.
     */
    private int next;
    
    /**
     * The constructor.
     */
    public ProgCounter() {
    	next= 0;
    }
    
    /**
     * Description of the method setTo.
     * @param nbr 
     */
    public void setTo(int nbr) {
    	next = nbr;
    }
     
    /**
     * Description of the method increase.
     */
    public void increase() {
    	next++;
    }
    public int getNext(){
    	return next;
    }
}
