/**
 * File generated from the NewModel::computer::Program uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import java.util.ArrayList;

import operation.Operation;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Program.
 */
@SuppressWarnings("serial")
public abstract class Program extends ArrayList<Operation> {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Program() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    public String toString(){
    	StringBuilder sb = new StringBuilder();
    	int count = 0;
    	for (Operation op : this){
    		sb.append(count + " ");
    		sb.append(op);
    		sb.append(System.getProperty("line.separator"));
    		count ++;
    	}
    	return sb.toString();
    }
    
}
