/**
 * File generated from the NewModel::computer::Program uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package computer;

import java.util.ArrayList;

import operation.Operation;


/**
 * Description of Program.
 */
@SuppressWarnings("serial")
public abstract class Program extends ArrayList<Operation> {

    
    /**
     * The constructor.
     */
    public Program() {
    	super();
    }
    
    public String toString(){
    	StringBuilder sb = new StringBuilder();
    	int count = 0;
    	for (Operation op : this){
    		sb.append(count + " ");
    		sb.append(op);
    		sb.append(System.getProperty("line.separator"));
    		count ++;
    	}
    	return sb.toString();
    }
    
}
