/**
 * File generated from the NewModel::operation::Add uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import operation.BinExpr;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Add.
 */
public class Add extends BinExpr {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Add() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
