/**
 * File generated from the NewModel::operation::Add uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import computer.Memory;

import operand.Word;
import operation.BinExpr;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Add.
 */
public class Add extends BinExpr {

    public Add() {

    }
    

	@Override
	public void typeOp(Memory memory) {
		address.getValue(memory).add(op1.getValue(memory), op2.getValue(memory));
		
//		dest.add(op1.getValue(memory),op2);
		
	}
    
    
}
