/**
 * File generated from the NewModel::operation::BinExpr uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import computer.Memory;
import computer.ProgCounter;
import operand.Operand;
import operand.Address;
import operand.Word;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of BinExpr.
 */
public abstract class BinExpr implements Operation {

    protected Operand op1;
    protected Operand op2;
    protected Address address;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public BinExpr(Operand op1, Operand op2, Address address) {
    	this.op1=op1;
    	this.op2=op2;
    	this.address=address;
    }
    
    /**
     * Description of the method typeOp.
     */
    public abstract void typeOp(Memory memory);
     
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
//    	Word dest = address.getValue(memory);
//    	Word word1 = op1.getValue(memory);
//    	Word word2 = op2.getValue(memory);
    	typeOp(memory);
    	
    }
    
    
}
