/**
 * File generated from the NewModel::operation::Copy uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import operand.Address;
import operand.Operand;
import operand.Word;
import computer.Memory;
import computer.ProgCounter;

/**
 * Description of Copy.
 */
public class Copy implements Operation {

    private Operand op1;
    private Address address;
    
    /**
     * The constructor.
     */
    public Copy(Operand op1, Address address) {
    	this.op1 = op1;
    	this.address = address;
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	address.getValue(memory).setValue(op1.getValue(memory));
    	progCounter.increase();
    }
    
    public String toString(){
    	return "CPY " + op1 + " " + address;
    }
}
