/**
 * File generated from the NewModel::operation::Copy uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import operand.Address;
// Start of user code (user defined imports)
import operand.Operand;

import computer.Memory;
import computer.ProgCounter;

// End of user code

/**
 * Description of Copy.
 */
public class Copy implements Operation {

    private Operand op1 = null;
    public Address address = null;
    
    /**
     * The constructor.
     */
    public Copy() {
    	super();

    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
 
    }
    
    
}
