/**
 * File generated from the NewModel::operation::Halt uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import computer.Memory;
import computer.ProgCounter;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Halt.
 */
public class Halt implements Operation {

    public Halt() {
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	progCounter.setTo(-1);
    }
    
    
}
