/**
 * File generated from the NewModel::operation::Halt uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Halt.
 */
public class Halt implements Operation {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Halt() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	// Start of user code for method exec
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
