/**
 * File generated from the NewModel::operation::Jump uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Jump.
 */
public class Jump implements Operation {
    /**
     * Description of the property jumpTo.
     */
    private Object jumpTo = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Jump() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	// Start of user code for method exec
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns jumpTo.
     * @return jumpTo 
     */
    public Object getJumpTo() {
    	return this.jumpTo;
    }
    
    /**
     * Sets a value to attribute jumpTo. 
     * @param newJumpTo 
     */
    public void setJumpTo(Object newJumpTo) {
        this.jumpTo = newJumpTo;
    }
    
    
}
