/**
 * File generated from the NewModel::operation::JumpEq uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import operand.Operand;
// Start of user code (user defined imports)

import computer.Memory;
import computer.ProgCounter;

// End of user code

/**
 * Description of JumpEq.
 */
public class JumpEq implements Operation {

    private int jumpTo;
    private Operand op1;
    private Operand op2;
    
    /**
     * The constructor.
     */
    public JumpEq(int jumpTo, Operand op1, Operand op2) {
    	this.jumpTo=jumpTo;
    	this.op1=op1;
    	this.op2=op2;
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	if(op1.getValue(memory).equals(op2.getValue(memory))){
    		progCounter.setTo(jumpTo);
    	}else {
    		progCounter.increase();
    	}
    }
    
    
}
