/**
 * File generated from the NewModel::operation::Jump uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import computer.Memory;
import computer.ProgCounter;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Jump.
 */
public class Jump implements Operation {
    /**
     * Description of the property jumpTo.
     */
    private int jumpTo;
    
    public Jump(int jumpTo) {
    	this.jumpTo=jumpTo;
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	progCounter.setTo(jumpTo);
    }
    
    public String toString(){
    	return "JMP " + jumpTo;
    }
}
