/**
 * File generated from the NewModel::operation::Operation uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import computer.Memory;
import computer.ProgCounter;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Operation.
 */
public interface Operation {
	// Start of user code (user defined attributes)
	
	// End of user code
	
	/**
	 * Description of the method exec.
	 * @param memory 
	 * @param progCounter 
	 */
	public void exec(Memory memory, ProgCounter progCounter);
	
	// Start of user code (user defined methods)
	
	// End of user code
	
}
