/**
 * File generated from the NewModel::operation::Operation uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import computer.Memory;
import computer.ProgCounter;


/**
 * Description of Operation.
 */
public interface Operation {
	
	/**
	 * Description of the method exec.
	 * @param memory 
	 * @param progCounter 
	 */
	public void exec(Memory memory, ProgCounter progCounter);
	
	public String toString();
}
