/**
 * File generated from the NewModel::operation::Print uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operation;

import operand.Operand;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Print.
 */
public class Print implements Operation {
    /**
     * Description of the property op.
     */
    private Operand op = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Print() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method exec.
     * @param memory 
     * @param progCounter 
     */
    public void exec(Memory memory, ProgCounter progCounter) {
    	// Start of user code for method exec
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns op.
     * @return op 
     */
    public Operand getOp() {
    	return this.op;
    }
    
    /**
     * Sets a value to attribute op. 
     * @param newOp 
     */
    public void setOp(Operand newOp) {
        this.op = newOp;
    }
    
    
}
