/**
 * File generated from the NewModel::operand::Address uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operand;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Address.
 */
public class Address implements Operand {
    /**
     * Description of the property address.
     */
    private Object address = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Address() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method getValue.
     */
    public void getValue() {
    	// Start of user code for method getValue
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns address.
     * @return address 
     */
    public Object getAddress() {
    	return this.address;
    }
    
    /**
     * Sets a value to attribute address. 
     * @param newAddress 
     */
    public void setAddress(Object newAddress) {
        this.address = newAddress;
    }
    
    
}
