/**
 * File generated from the NewModel::operand::Operand uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operand;

import computer.Memory;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Operand.
 */
public interface Operand {
	// Start of user code (user defined attributes)
	
	// End of user code
	
	/**
	 * Description of the method getValue.
	 */
	public Word getValue(Memory memory);
	
	// Start of user code (user defined methods)
	
	// End of user code
	
}
