/**
 * File generated from the NewModel::operand::Operand uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operand;

import computer.Memory;

/**
 * Description of Operand.
 */
public interface Operand {

	
	/**
	 * Description of the method getValue.
	 */
	public Word getValue(Memory memory);
	
	public String toString();

	
}
