/**
 * File generated from the NewModel::operand::Word uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operand;

import operand.Operand;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Word.
 */
public abstract class Word implements Operand {

    public Word() {

    }
    
    public abstract void add(Operand op1, Operand op2);
    public abstract void mul(Operand op1, Operand op2);
     
    /**
     * Description of the method getValue.
     */
    
 
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
