/**
 * File generated from the NewModel::operand::Word uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package operand;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Word.
 */
public abstract class Word implements Operand {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Word() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method getValue.
     */
    public abstract Word getValue();
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
